spring:
  application:
    name: Review-service
  datasource:
    url: jdbc:postgresql://localhost:5433/code_review_app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          bitbucket:
            client-id: agkLVpvpHWfav2J9BY
            client-secret: ff7RctV6eH2T2KckLkhk4yjJ57WtnKbu
            scope: account,repository,pullrequest,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          bitbucket:
            authorization-uri: https://bitbucket.org/site/oauth2/authorize
            token-uri: https://bitbucket.org/site/oauth2/access_token
            user-info-uri: https://api.bitbucket.org/2.0/user
            user-name-attribute: username
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

bitbucket:
  username: antonrotaru-admin
  password: ATBBqHafzmYDGdDxeYh2wXW3Kc7R6EAF1E96

chatgpt:
  api-url: https://api.openai.com/v1/chat/completions
  api-key: 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
  model: gpt-3.5-turbo

logging:
  level:
    liquibase: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web: DEBUG