spring:
  application:
    name: Review-service
  datasource:
    url: jdbc:postgresql://localhost:5433/code_review_app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none

bitbucket:
  username: antonrotaru-admin
  password: ATBBqHafzmYDGdDxeYh2wXW3Kc7R6EAF1E96

chatgpt:
  api-url: https://api.openai.com/v1/chat/completions
  api-key: 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
  model: gpt-3.5-turbo

logging:
  level:
    liquibase: DEBUG