spring:
  application:
    name: Review-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          bitbucket-login:
            provider: bitbucket
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BITBUCKET_LOGIN_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BITBUCKET_LOGIN_CLIENT_SECRET}
            scope: account,repository,pullrequest,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          bitbucket-signup:
            provider: bitbucket
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BITBUCKET_SIGNUP_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BITBUCKET_SIGNUP_CLIENT_SECRET}
            scope: account,repository,pullrequest,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          bitbucket:
            authorization-uri: https://bitbucket.org/site/oauth2/authorize
            token-uri: https://bitbucket.org/site/oauth2/access_token
            user-info-uri: https://api.bitbucket.org/2.0/user
            user-name-attribute: username

bitbucket:
  username: ${BITBUCKET_USERNAME}
  password: ${BITBUCKET_PASSWORD}

app:
  ai:
    chatgpt:
      api-url: ${APP_AI_CHATGPT_API_URL}
      api-key: ${APP_AI_CHATGPT_API_KEY}

    grok:
      api-url: ${APP_AI_GROK_API_URL}
      api-key: ${APP_AI_GROK_API_KEY}

    copilot:
      api-url: ${APP_AI_COPILOT_API_URL}
      api-key: ${APP_AI_COPILOT_API_KEY}

    gemini:
      api-url: ${APP_AI_GEMINI_API_URL}
      api-key: ${APP_AI_GEMINI_API_KEY}

logging:
  level:
    liquibase: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web: DEBUG

frontend:
  url: ${FRONTEND_URL}
